[build-system]
requires = ["setuptools",
            "wheel"]

build-backend = 'setuptools.build_meta'

[project]
name = "AgriFoodPy"
version = "0.2.1"
description = "A package for modelling food systems"
readme = "README.md"
requires-python = ">=3.9"

authors = [
    {name = "Juan Pablo Cordero", email = "juanpablo.cordero@york.ac.uk"},
    {name = "Sarah L. Bridle", email = "sarah@sarahbridle.net"}
]

license = "BSD-3-Clause"
license-files = ["LICENSE.rst"]

dependencies = [
    "numpy",
    "pandas",
    "xarray",
    "matplotlib"
]

[project.urls]
Homepage = "https://github.com/FixOurFood/AgriFoodPy"
Documentation = "https://agrifoodpy.readthedocs.io"

[tool.setuptools.packages.find]
where = ["."]